# Generated by Django 3.1.7 on 2021-03-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210315_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
