# Generated by Django 3.1.7 on 2021-03-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20210316_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='applayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField()),
                ('cv', models.FileField(upload_to='')),
                ('cover_letter', models.TextField(max_length=1000)),
            ],
        ),
    ]
